### ISSUE TITLE
starter notebook appear corrupted

### ISSUE THREAD

**Issue by smartinsightsfromdata** [RasaHQ/rasa-workshop#2]
@Resseguie @JustinaPetr  The starter notebook appears to be corrupted.  The `exercise` one works fine.

**Comment by JustinaPetr** [comment]
Thanks for reporting this! I will look into this ASAP

**Comment by smartinsightsfromdata** [comment]
@JustinaPetr ping  :)

**Comment by hsm207** [comment]
@JustinaPetr @smartinsightsfromdata  I've made a pull request (#4 ) that fixes this issue.
